spring:
  datasource:
    url: jdbc:mysql://plantpal-db.clwo0ukaumfj.eu-north-1.rds.amazonaws.com:3306/plantpal_db
    username: admin
    password: PlantPal123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: plantpal

server:
  port: 8080